<b:skin><![CDATA[/*
-----------------------------------------------
Blogger Template Style
Name:     Awesome Inc.
Designer: Tina Chen
URL:      tinachen.org
----------------------------------------------- */

/* Variable definitions
   ====================
   {% include "Variable.xhtml" %}
*/

/* Content
----------------------------------------------- */
  {% include "baseStyle.scss" %}
]]></b:skin>